#!/usr/bin/env python3
"""
Visualise computeSeedPose() test results from seed_output.csv.

Reads the CSV generated by the standalone C++ test (main.cpp) and creates:
  1. An individual subplot for each test case
  2. A combined overview plot with all test cases overlaid

Usage:
    python visualize.py                    # uses seed_output.csv in current dir
    python visualize.py path/to/output.csv # custom CSV path

Dependencies:
    numpy, matplotlib
"""

import csv
import math
import sys
from dataclasses import dataclass
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
from typing import List, Tuple


# ═══════════════════════════════════════════════════════════════════════
#  1. Field Definitions  —  LabLarge
# ═══════════════════════════════════════════════════════════════════════

FIELD_LENGTH = 6300.0
FIELD_WIDTH = 4050.0
HALF_L = FIELD_LENGTH / 2.0
HALF_W = FIELD_WIDTH / 2.0
GOAL_BOX_LENGTH = 450.0
GOAL_BOX_WIDTH = 1800.0
PENALTY_BOX_LENGTH = 1350.0
PENALTY_BOX_WIDTH = 2700.0
CENTER_CIRCLE_DIAMETER = 1350.0
CORNER_ARC_RADIUS = 225.0
M_PI = math.pi


# ═══════════════════════════════════════════════════════════════════════
#  2. Field Drawing
# ═══════════════════════════════════════════════════════════════════════

def draw_field(ax):
    """Draw a RoboCup field diagram on the given axes."""
    # Green carpet
    ax.add_patch(plt.Rectangle(
        (-HALF_L, -HALF_W), FIELD_LENGTH, FIELD_WIDTH,
        facecolor='#2e7d32', edgecolor='white', linewidth=2, zorder=1
    ))

    # Centre line
    ax.plot([0, 0], [-HALF_W, HALF_W], color='white', linewidth=2, zorder=2)

    # Centre circle
    centre_circle = plt.Circle(
        (0, 0), CENTER_CIRCLE_DIAMETER / 2.0,
        facecolor='none', edgecolor='white', linewidth=2, zorder=2
    )
    ax.add_patch(centre_circle)

    # Goal boxes: start at goal line and extend INWARD
    # Left side:  x from -HALF_L to -HALF_L + GOAL_BOX_LENGTH
    # Right side: x from  HALF_L - GOAL_BOX_LENGTH to HALF_L
    half_gbw = GOAL_BOX_WIDTH / 2.0
    ax.add_patch(plt.Rectangle(
        (-HALF_L, -half_gbw), GOAL_BOX_LENGTH, GOAL_BOX_WIDTH,
        facecolor='none', edgecolor='white', linewidth=2, zorder=2
    ))
    ax.add_patch(plt.Rectangle(
        (HALF_L - GOAL_BOX_LENGTH, -half_gbw), GOAL_BOX_LENGTH, GOAL_BOX_WIDTH,
        facecolor='none', edgecolor='white', linewidth=2, zorder=2
    ))

    # Penalty boxes: start at goal line and extend INWARD
    # Left side:  x from -HALF_L to -HALF_L + PENALTY_BOX_LENGTH
    # Right side: x from  HALF_L - PENALTY_BOX_LENGTH to HALF_L
    half_pbw = PENALTY_BOX_WIDTH / 2.0
    ax.add_patch(plt.Rectangle(
        (-HALF_L, -half_pbw), PENALTY_BOX_LENGTH, PENALTY_BOX_WIDTH,
        facecolor='none', edgecolor='white', linewidth=2, zorder=2
    ))
    ax.add_patch(plt.Rectangle(
        (HALF_L - PENALTY_BOX_LENGTH, -half_pbw), PENALTY_BOX_LENGTH, PENALTY_BOX_WIDTH,
        facecolor='none', edgecolor='white', linewidth=2, zorder=2
    ))

    # Goals (goal posts)
    half_goal_width = 760.0
    for sign in [-1, 1]:
        gx = sign * HALF_L
        ax.plot([gx, gx], [-half_goal_width, half_goal_width],
                color='white', linewidth=3, zorder=2)


def draw_feature_arrow(ax, x, y, orientation, color, label=None, zorder=5):
    """Draw a field feature with its orientation arrow."""
    ax.scatter(x, y, marker='s', s=60, color=color, edgecolors='white',
               linewidths=1.5, zorder=zorder)
    arrow_len = 250
    dx = arrow_len * math.cos(orientation)
    dy = arrow_len * math.sin(orientation)
    ax.arrow(x, y, dx, dy, head_width=80, head_length=100,
             fc=color, ec=color, linewidth=1.5, zorder=zorder, alpha=0.7)
    if label:
        ax.annotate(label, xy=(x, y), xytext=(x + dx + 40, y + dy + 40),
                    fontsize=7, color=color, fontweight='bold',
                    bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                              edgecolor=color, alpha=0.8),
                    arrowprops=dict(arrowstyle='->', color=color, lw=0.8),
                    zorder=zorder)


# ═══════════════════════════════════════════════════════════════════════
#  3. Load Results
# ═══════════════════════════════════════════════════════════════════════

@dataclass
class Result:
    idx: int
    feature_type: str
    ff_x: float
    ff_y: float
    ff_orientation: float
    obs_distance: float
    obs_heading: float
    obs_orientation: float
    computed_x: float
    computed_y: float
    computed_theta: float
    robot_x: float
    robot_y: float
    robot_theta: float
    error_x: float
    error_y: float
    error_theta: float
    error_position: float
    passed: bool


def load_results(csv_path: str) -> List[Result]:
    results = []
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            results.append(Result(
                idx=int(row['test_idx']),
                feature_type=row['feature_type'],
                ff_x=float(row['ff_x']),
                ff_y=float(row['ff_y']),
                ff_orientation=float(row['ff_orientation']),
                obs_distance=float(row['obs_distance']),
                obs_heading=float(row['obs_heading']),
                obs_orientation=float(row['obs_orientation']),
                computed_x=float(row['computed_x']),
                computed_y=float(row['computed_y']),
                computed_theta=float(row['computed_theta']),
                robot_x=float(row['robot_x']),
                robot_y=float(row['robot_y']),
                robot_theta=float(row['robot_theta']),
                error_x=float(row['error_x']),
                error_y=float(row['error_y']),
                error_theta=float(row['error_theta']),
                error_position=float(row['error_position']),
                passed=bool(int(row['passed'])),
            ))
    return results


# ═══════════════════════════════════════════════════════════════════════
#  4. Visualisation
# ═══════════════════════════════════════════════════════════════════════

FEATURE_COLORS = {
    'fCorner': '#e53935',
    'fTJunction': '#8e24aa',
    'fXJunction': '#ffb300',
    'fCentreCircle': '#00acc1',
}


def visualise_results(results: List[Result]):
    n_tests = len(results)
    n_cols = 4
    n_rows = (n_tests + n_cols - 1) // n_cols

    # ── Individual subplots ──
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4.5))
    axes = axes.flatten()

    for idx, r in enumerate(results):
        ax = axes[idx]
        status = "PASS" if r.passed else "FAIL"

        draw_field(ax)

        # Feature marker
        fc = FEATURE_COLORS.get(r.feature_type, '#333333')
        draw_feature_arrow(ax, r.ff_x, r.ff_y, r.ff_orientation, fc,
                           label=r.feature_type)

        # Observation line (robot -> feature)
        ax.plot([r.robot_x, r.ff_x], [r.robot_y, r.ff_y],
                color=fc, linewidth=1.0, linestyle=':', alpha=0.5, zorder=3)

        # Known robot pose
        arrow_len = 250
        rdx = arrow_len * math.cos(r.robot_theta)
        rdy = arrow_len * math.sin(r.robot_theta)
        ax.arrow(r.robot_x, r.robot_y, rdx, rdy,
                 head_width=80, head_length=100, fc='#1565c0', ec='#1565c0',
                 linewidth=2, zorder=7, alpha=0.8)
        ax.scatter(r.robot_x, r.robot_y, marker='o', s=60,
                   color='#1565c0', edgecolors='white', linewidths=1.5, zorder=7,
                   label='Robot (known)' if idx == 0 else '')

        # Computed pose (should overlap identically if PASS)
        cdx = arrow_len * math.cos(r.computed_theta)
        cdy = arrow_len * math.sin(r.computed_theta)
        ax.arrow(r.computed_x, r.computed_y, cdx, cdy,
                 head_width=60, head_length=80, fc='#ff6f00', ec='#ff6f00',
                 linewidth=1.5, zorder=6, alpha=0.7, linestyle='--')
        ax.scatter(r.computed_x, r.computed_y, marker='o', s=40,
                   color='#ff6f00', edgecolors='white', linewidths=1, zorder=6,
                   label='Computed' if idx == 0 else '')

        err_label = f"err={r.error_position:.2f}mm" if not r.passed else ""
        ax.set_title(f"Test {idx+1}: {status}\n{r.feature_type}\n{err_label}",
                     fontsize=9, fontweight='bold',
                     color='green' if r.passed else 'red')
        ax.set_xlabel('X (mm)', fontsize=8)
        ax.set_ylabel('Y (mm)', fontsize=8)
        ax.set_aspect('equal')
        margin = 600
        ax.set_xlim(-HALF_L - margin, HALF_L + margin)
        ax.set_ylim(-HALF_W - margin, HALF_W + margin)
        ax.grid(True, alpha=0.1, linestyle='--')
        ax.tick_params(labelsize=7)

    # Hide unused subplots
    for idx in range(n_tests, len(axes)):
        axes[idx].set_visible(False)

    fig.suptitle("computeSeedPose() — Per-Test Visualisation",
                 fontsize=14, fontweight='bold', y=1.01)
    fig.tight_layout()
    fig.savefig('seed_geometry_tests.png', dpi=150, bbox_inches='tight')
    print(f"  Saved: seed_geometry_tests.png")

    # ── Combined overview ──
    fig2, ax2 = plt.subplots(figsize=(14, 10))
    draw_field(ax2)

    legend_elements = []

    for idx, r in enumerate(results):
        fc = FEATURE_COLORS.get(r.feature_type, '#333333')

        # Feature marker
        ax2.scatter(r.ff_x, r.ff_y,
                    marker='o', s=80, color=fc, edgecolors='white',
                    linewidths=1.5, zorder=6, alpha=0.7)

        # Observation line
        ax2.plot([r.robot_x, r.ff_x], [r.robot_y, r.ff_y],
                 color=fc, linewidth=1.0, linestyle=':', alpha=0.5, zorder=3)

        # Robot pose (coloured by test index)
        color = plt.cm.tab10(idx / max(n_tests - 1, 1))
        arrow_len = 300
        rdx = arrow_len * math.cos(r.robot_theta)
        rdy = arrow_len * math.sin(r.robot_theta)
        ax2.arrow(r.robot_x, r.robot_y, rdx, rdy,
                  head_width=100, head_length=120, fc=color, ec=color,
                  linewidth=2, zorder=7, alpha=0.8)
        ax2.scatter(r.robot_x, r.robot_y, marker='o', s=50,
                    color=color, edgecolors='white', linewidths=1.5, zorder=7)

        # Test number label
        ax2.annotate(
            str(idx + 1),
            xy=(r.robot_x, r.robot_y),
            xytext=(r.robot_x + rdx + 50, r.robot_y + rdy + 50),
            fontsize=8, color=color, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='white',
                      edgecolor=color, alpha=0.8),
            arrowprops=dict(arrowstyle='->', color=color, lw=1.0),
            zorder=8
        )

        legend_elements.append(
            mpatches.Patch(color=color, label=f"Test {idx+1}")
        )

    # Feature type legend
    for ft, fc in FEATURE_COLORS.items():
        legend_elements.append(
            mpatches.Patch(color=fc, label=f'Observed {ft}', alpha=0.7)
        )

    legend_elements.append(
        mpatches.Patch(color='#1565c0', label='Known robot pose'))
    legend_elements.append(
        mpatches.Patch(color='#ff6f00', label='Computed pose'))

    ax2.legend(handles=legend_elements, loc='upper right', fontsize=8,
               framealpha=0.9, ncol=2)

    ax2.set_title(f"computeSeedPose() — Combined Overview ({n_tests} test cases)",
                  fontsize=14, fontweight='bold')
    ax2.set_xlabel('X (mm)', fontsize=11)
    ax2.set_ylabel('Y (mm)', fontsize=11)
    ax2.set_aspect('equal')
    margin = 800
    ax2.set_xlim(-HALF_L - margin, HALF_L + margin)
    ax2.set_ylim(-HALF_W - margin, HALF_W + margin)
    ax2.grid(True, alpha=0.15, linestyle='--')

    fig2.tight_layout()
    fig2.savefig('seed_geometry_overview.png', dpi=150, bbox_inches='tight')
    print(f"  Saved: seed_geometry_overview.png")


# ═══════════════════════════════════════════════════════════════════════
#  5. Main
# ═══════════════════════════════════════════════════════════════════════

def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else 'seed_output.csv'

    if not Path(csv_path).exists():
        print(f"ERROR: CSV file not found: {csv_path}")
        print("Run the C++ test first: ./compile.sh")
        sys.exit(1)

    print(f"Loading results from: {csv_path}")
    results = load_results(csv_path)
    print(f"  {len(results)} test cases loaded")

    passed = sum(1 for r in results if r.passed)
    print(f"  {passed}/{len(results)} passed")
    print()

    print("Rendering visualisations...")
    visualise_results(results)
    print("Done.")


if __name__ == '__main__':
    main()
